# Generated by Django 3.1.5 on 2021-01-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Ж', 'женский'), ('М', 'мужской')], max_length=15)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Ж', 'женский'), ('М', 'мужской')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('ожидается', 'ожидается'), ('отменён', 'отменён'), ('в процессе', 'в процессе'), ('завершён', 'завершён')], max_length=15)),
                ('from_place', models.CharField(max_length=150)),
                ('to_place', models.CharField(max_length=150)),
                ('car_class', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Ж', 'женский'), ('М', 'мужской')], max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.order')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.client')),
            ],
        ),
    ]
