# Generated by Django 3.1.5 on 2021-01-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0006_auto_20210116_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_place',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_place',
            field=models.CharField(max_length=150),
        ),
    ]
