# Generated by Django 3.1.5 on 2021-01-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0008_auto_20210116_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcard',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='operator_id',
            new_name='operator',
        ),
        migrations.AlterField(
            model_name='order',
            name='car_class',
            field=models.CharField(choices=[('эконом', 'эконом'), ('комфорт', 'комфорт'), ('премиум', 'премиум')], max_length=15),
        ),
    ]
