# Generated by Django 3.1.5 on 2021-01-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0009_auto_20210116_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
