# Generated by Django 3.1.5 on 2021-07-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0011_auto_20210708_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='order',
            new_name='order_id',
        ),
    ]
