# Generated by Django 3.1.5 on 2021-01-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Street',
        ),
    ]
