# Generated by Django 3.1.5 on 2021-01-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0002_auto_20210116_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='rudder',
            new_name='wheel_side',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='gearbox',
            field=models.CharField(choices=[('автомат', 'автомат'), ('механика', 'механика')], max_length=15),
        ),
    ]
