# Generated by Django 3.1.5 on 2021-01-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0005_auto_20210116_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetails',
            new_name='CarDetail',
        ),
    ]
