# Generated by Django 3.1.5 on 2021-01-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0008_auto_20210116_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablecar',
            old_name='street_id',
            new_name='street',
        ),
    ]
