# Generated by Django 3.1.5 on 2021-01-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0009_auto_20210116_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('эконом', 'эконом'), ('комфорт', 'комфорт'), ('премиум', 'премиум')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
