# Generated by Django 3.1.5 on 2021-01-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0009_auto_20210116_0400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetail',
            new_name='ModelDetail',
        ),
    ]
