# Generated by Django 3.1.5 on 2021-07-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0010_auto_20210118_0306'),
        ('driver_side', '0010_car_car_class'),
    ]

    operations = [
    ]
