# Generated by Django 3.1.5 on 2021-07-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0013_auto_20210708_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model_details',
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_side.modeldetail'),
        ),
    ]
