# Generated by Django 3.1.5 on 2021-07-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0013_modeldetail_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablecar',
            old_name='car_id',
            new_name='car_number',
        ),
    ]
