# Generated by Django 3.1.5 on 2021-07-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0014_auto_20210709_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldetail',
            old_name='engine',
            new_name='fuel_volume',
        ),
    ]
