# Generated by Django 3.1.5 on 2021-07-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0014_auto_20210708_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_details',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='driver_side.modeldetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(max_length=150),
        ),
    ]
