# Generated by Django 3.1.5 on 2021-07-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0015_auto_20210708_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model_details',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='modeldetail',
            name='model_name',
        ),
    ]
