# Generated by Django 3.1.5 on 2021-07-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0016_auto_20210708_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='driver_side.modeldetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeldetail',
            name='model_name',
            field=models.CharField(default='0', max_length=150),
            preserve_default=False,
        ),
    ]
