# Generated by Django 3.1.5 on 2021-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side', '0017_auto_20210708_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='model_details',
        ),
        migrations.RemoveField(
            model_name='modeldetail',
            name='model_name',
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        )
    ]
