# Generated by Django 3.1.5 on 2021-07-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_side'),
        ('driver_side'),
    ]

    operations = [
    ]
